#!/bin/bash
set -euo pipefail

REPO_DIR="${REPO_DIR:-$HOME/cert-qlora-MI/llm-sequence-mi-remote}"
cd "$REPO_DIR"

CONDA_ENV="${CONDA_ENV:-/anvil/projects/x-cis230270/x-sangdembay/conda_envs/cert-qlora-qwen3}"
CONFIG="${CONFIG:-configs/qwen3_8b_qlora_session_targeted.yaml}"
DATA_DIR="${DATA_DIR:-/anvil/projects/x-cis230270/x-sangdembay/cert-qlora-MI/outputs/session_jsonl_r42}"
CHECKPOINT_ROOT="${CHECKPOINT_ROOT:-/anvil/projects/x-cis230270/x-sangdembay/cert-qlora-MI/checkpoints/qwen3_8b_session_qlora_r42_ddp_mb22_gc_on}"
TOKEN_CACHE_ROOT="${TOKEN_CACHE_ROOT:-/anvil/projects/x-cis230270/x-sangdembay/cert-qlora-MI/token_delta_cache/qwen3_8b_session_token_deltas_r42_mb22_gc_on}"
FRONTIER_ROOT="${FRONTIER_ROOT:-/anvil/projects/x-cis230270/x-sangdembay/cert-qlora-MI/outputs/token_delta_sae_frontier_qwen3_8b_r42_mb22_gc_on}"

NPROC="${NPROC:-4}"
MICRO_BS="${MICRO_BS:-22}"
GRAD_ACCUM="${GRAD_ACCUM:-1}"
GC_MODE="${GC_MODE:-on}"
ATTN_IMPL="${ATTN_IMPL:-sdpa}"
EVAL_STRATEGY="${EVAL_STRATEGY:-no}"
SAVE_STEPS="${SAVE_STEPS:-1000}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"
IGNORE_DATA_SKIP="${IGNORE_DATA_SKIP:-0}"
SKIP_RNG_STATE_RESUME="${SKIP_RNG_STATE_RESUME:-0}"

EXTRACT_LAYERS="${EXTRACT_LAYERS:-18,26,34}"
EXTRACT_BATCH_SIZE="${EXTRACT_BATCH_SIZE:-4}"
EXTRACT_CHUNK_EXAMPLES="${EXTRACT_CHUNK_EXAMPLES:-512}"
SAE_MAX_ROWS="${SAE_MAX_ROWS:-2000000}"
SAE_BATCH_SIZE="${SAE_BATCH_SIZE:-4096}"
LATENT_MULTIPLIERS="${LATENT_MULTIPLIERS:-2,4}"
TOPK_VALUES="${TOPK_VALUES:-4,8}"

DATA_DIR="$DATA_DIR" \
CHECKPOINT_ROOT="$CHECKPOINT_ROOT" \
TOKEN_CACHE_ROOT="$TOKEN_CACHE_ROOT" \
FRONTIER_ROOT="$FRONTIER_ROOT" \
CONDA_ENV="$CONDA_ENV" \
CONFIG="$CONFIG" \
NPROC="$NPROC" \
MICRO_BS="$MICRO_BS" \
GRAD_ACCUM="$GRAD_ACCUM" \
GC_MODE="$GC_MODE" \
ATTN_IMPL="$ATTN_IMPL" \
EVAL_STRATEGY="$EVAL_STRATEGY" \
SAVE_STEPS="$SAVE_STEPS" \
RESUME_FROM_CHECKPOINT="$RESUME_FROM_CHECKPOINT" \
IGNORE_DATA_SKIP="$IGNORE_DATA_SKIP" \
SKIP_RNG_STATE_RESUME="$SKIP_RNG_STATE_RESUME" \
EXTRACT_LAYERS="$EXTRACT_LAYERS" \
EXTRACT_BATCH_SIZE="$EXTRACT_BATCH_SIZE" \
EXTRACT_CHUNK_EXAMPLES="$EXTRACT_CHUNK_EXAMPLES" \
SAE_MAX_ROWS="$SAE_MAX_ROWS" \
SAE_BATCH_SIZE="$SAE_BATCH_SIZE" \
LATENT_MULTIPLIERS="$LATENT_MULTIPLIERS" \
TOPK_VALUES="$TOPK_VALUES" \
REPO_DIR="$REPO_DIR" \
  bash scripts/submit_qwen3_8b_targeted_pipeline_anvil.sh
